port: 8070
adminPort: 8060

log:
  logPath: ./logs
  logName: jugglechat-server

mysql:
  user: root
  password: 123456
  address: 192.168.154.146:3306
  name: im_db
  debug: true

# imsdk im长连接网关地址
imApiDomain: http://127.0.0.1:9003
imAdminDomain: http://127.0.0.1:8090

botConnector:
  domain: <bot-connector url>

commercial: false